### ISSUE TITLE
OpenHAB 4 Support

### ISSUE THREAD

**Issue by itbeyond** [tomitan100/org.openhab.binding.bom#11]
Is there any updates or information on running this on OH4. I just upgraded but it appears the 3.2.1 binding does not work. It starts to work and falls over as below:

```
2023-09-27 23:51:53.495 [INFO ] [nhab.binding.bom.internal.BomHandler] - Cancelling observation refresh job
2023-09-27 23:51:53.496 [INFO ] [nhab.binding.bom.internal.BomHandler] - Cancelling forecast refresh job
2023-09-27 23:51:53.490 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'bom:weather:swanbourne' changed from UNKNOWN to UNINITIALIZED
2023-09-27 23:51:53.500 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'bom:weather:swanbourne' changed from UNINITIALIZED to UNINITIALIZED (DISABLED)
2023-09-27 23:51:54.802 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'bom:weather:swanbourne' changed from UNINITIALIZED (DISABLED) to INITIALIZING
2023-09-27 23:51:54.808 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'bom:weather:swanbourne' changed from INITIALIZING to UNKNOWN
2023-09-27 23:51:56.440 [INFO ] [nhab.binding.bom.internal.BomHandler] - Processing precis forecast from FTP path: ftp://ftp.bom.gov.au/anon/gen/fwo/IDW14199.xml, area ID: WA_PT058
	at org.openhab.binding.bom.internal.BomHandler.updateChannelState(BomHandler.java:535) ~[?:?]
	at org.openhab.binding.bom.internal.BomHandler.lambda$2(BomHandler.java:181) ~[?:?]
	at org.openhab.binding.bom.internal.BomHandler.refreshObservation(BomHandler.java:178) ~[?:?]
2023-09-27 23:51:56.441 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'BOM_Swanbourne_WeatherStation' updated to Swanbourne
2023-09-27 23:51:56.441 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'BOM_Swanbourne_WeatherStation' changed from NULL to Swanbourne
2023-09-27 23:51:56.443 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'BOM_Swanbourne_ObservationDateAndTime' updated to 2023-09-27T23:40:00.000+0800
2023-09-27 23:51:56.444 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'BOM_Swanbourne_ObservationDateAndTime' changed from NULL to 2023-09-27T23:40:00.000+0800
	at org.openhab.binding.bom.internal.BomHandler.updateChannelState(BomHandler.java:535) ~[?:?]
	at org.openhab.binding.bom.internal.BomHandler.lambda$3(BomHandler.java:496) ~[?:?]
	at org.openhab.binding.bom.internal.BomHandler.updateForecastState(BomHandler.java:478) ~[?:?]
	at org.openhab.binding.bom.internal.BomHandler.refreshPrecisForecast(BomHandler.java:335) ~[?:?]
	at org.openhab.binding.bom.internal.BomHandler.refreshForecast(BomHandler.java:241) ~[?:?]
```
The status of the binding in the UI states: UNKNOWN

**Comment by itbeyond** [comment]
Found a version 4 update in this post https://community.openhab.org/t/solved-australian-bureau-of-meteorology-weather-forecast-binding/68230/135
