### ISSUE TITLE
OpenHAB 3.0 java error

### ISSUE THREAD

**Issue by tehsquid** [tomitan100/org.openhab.binding.bom#7]
Hi Tom,

Recently started fresh with OpenHAB 3.0, having some issues with getting the 3.0 binding to run.  When starting, log file shows:

`2021-01-16 15:49:11.528 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.bom-3.0.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.bom [208]
  Unresolved requirement: Import-Package: org.apache.commons.lang; version="[2.6.0,3.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]`

I have checked JRE is installed correctly, java --version shows:

`openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)`

.jar file should be readable/executable as well.

Let me know if I can do anything else to assist with troubleshooting - perhaps I have the wrong JRE installed?

Thanks,

Alex

**Comment by tomitan100** [comment]
Hi Alex,

What machine are you running openHAB in?  Also have you tried Oralce JRE?  That seems to be the one that is recommended.

Regards,
Tom

**Comment by tehsquid** [comment]
Oracle java seemed to sort me out - thanks.

As a note - the docs for installation seem to lean you towards Azul Zulu: https://www.openhab.org/docs/installation/#prerequisites

Thanks again!
